### ISSUE TITLE
run SimiFeat on a custom dataset

### ISSUE THREAD

**Issue by bakachan19** [UCSC-REAL/SimiFeat#2]
Hi.
I would like to use your method to check whether a custom dataset has errors in the labeling.
Is it possible to run the SimiFeat method on a custom dataset (different from CIFAR10/100) for which I do not know whether the labels are noisy or not? If so, could you please provide some piece of code to this? (something like the Clothing1M experiments)

Thank you for your time and help.

**Comment by zwzhu-d** [comment]
Yes. Please refer to [this repo](https://github.com/Docta-ai/docta).

**Comment by bakachan19** [comment]
Thank you!
